# Generated by Django 4.2.21 on 2026-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('download', 'Download'), ('print', 'Print'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('password_protection', 'Password Protection')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['feature'],
            },
        ),
    ]
